import * as XLSX from "xlsx";
import type { KPI, SeriesPoint, ChartOverlays } from "@easykpi/shared/types";
import { getFormula } from "@easykpi/shared/formulas";

export interface ExcelExportOptions {
  kpi: KPI;
  data: SeriesPoint[];
  overlays?: ChartOverlays;
  workspace?: string;
  generatedBy?: string;
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function timestamp(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}-${pad(
    d.getHours(),
  )}${pad(d.getMinutes())}`;
}

/**
 * Phase 1 per-chart Excel export.
 * Single sheet: metadata rows + data table including overlays when present.
 */
export function exportChartToExcel(opts: ExcelExportOptions): void {
  const { kpi, data, overlays, workspace, generatedBy } = opts;
  const formula = getFormula(kpi.id);

  const metadataRows: (string | number)[][] = [
    ["KPI", kpi.name],
    ["ID", kpi.id],
    ["Category", kpi.category],
    ["Type", kpi.type],
    ["Formula", formula?.formula ?? ""],
    ["Unit", formula?.unit ?? ""],
    ["Precision", formula?.precision ?? 2],
    ["Workspace", workspace ?? ""],
    ["Generated by", generatedBy ?? ""],
    ["Generated at", new Date().toISOString()],
    [],
  ];

  const header = ["period", "value"];
  if (overlays?.target) header.push("target");
  if (overlays?.bands) header.push("benchmark_p25", "benchmark_p50", "benchmark_p75");
  if (overlays?.forecast) header.push("forecast", "forecast_low", "forecast_high");
  if (overlays?.anomalies) header.push("anomaly");

  const forecastByPeriod = new Map(
    (overlays?.forecast?.points ?? []).map((p) => [p.period, p.value] as const),
  );
  const forecastLowByPeriod = new Map(
    (overlays?.forecast?.low ?? []).map((p) => [p.period, p.value] as const),
  );
  const forecastHighByPeriod = new Map(
    (overlays?.forecast?.high ?? []).map((p) => [p.period, p.value] as const),
  );
  const anomalyByPeriod = new Map(
    (overlays?.anomalies ?? []).map((a) => [a.period, a.severity] as const),
  );

  const rows: (string | number | null)[][] = [];
  const allPeriods = [
    ...data.map((p) => p.period),
    ...(overlays?.forecast?.points ?? []).map((p) => p.period),
  ];
  const uniquePeriods = Array.from(new Set(allPeriods));
  for (const period of uniquePeriods) {
    const actual = data.find((p) => p.period === period);
    const row: (string | number | null)[] = [period, actual?.value ?? null];
    if (overlays?.target) row.push(overlays.target.value);
    if (overlays?.bands) {
      row.push(overlays.bands.p25, overlays.bands.p50, overlays.bands.p75);
    }
    if (overlays?.forecast) {
      row.push(
        forecastByPeriod.get(period) ?? null,
        forecastLowByPeriod.get(period) ?? null,
        forecastHighByPeriod.get(period) ?? null,
      );
    }
    if (overlays?.anomalies) row.push(anomalyByPeriod.get(period) ?? "");
    rows.push(row);
  }

  const aoa = [...metadataRows, header, ...rows];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws["!freeze"] = { xSplit: 0, ySplit: metadataRows.length + 1 };
  ws["!cols"] = header.map(() => ({ wch: 16 }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, kpi.name.slice(0, 31));

  const filename = `${slugify(kpi.name)}-${timestamp()}.xlsx`;
  XLSX.writeFile(wb, filename);
}

/**
 * Dashboard-level multi-sheet export (client-side MVP).
 * The Phase 6 rich version with embedded chart PNGs moves to the server
 * (ExcelJS + headless ECharts) once apps/api ships.
 */
export function exportDashboardToExcel(opts: {
  dashboardName: string;
  workspace?: string;
  tiles: { kpi: KPI; data: SeriesPoint[]; overlays?: ChartOverlays }[];
}): void {
  const { dashboardName, workspace, tiles } = opts;
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryHeader = ["KPI", "Category", "Latest", "Target", "Status", "Unit"];
  const summaryRows = tiles.map((t) => {
    const latest = t.data[t.data.length - 1]?.value ?? null;
    const target = t.overlays?.target?.value ?? null;
    const formula = getFormula(t.kpi.id);
    let status: string = "—";
    if (latest !== null && target !== null) {
      status = latest >= target ? "OK" : latest >= target * 0.9 ? "WARN" : "CRITICAL";
    }
    return [t.kpi.name, t.kpi.category, latest, target, status, formula?.unit ?? ""];
  });
  const summary = XLSX.utils.aoa_to_sheet([
    ["Dashboard", dashboardName],
    ["Workspace", workspace ?? ""],
    ["Generated at", new Date().toISOString()],
    [],
    summaryHeader,
    ...summaryRows,
  ]);
  summary["!cols"] = summaryHeader.map(() => ({ wch: 18 }));
  XLSX.utils.book_append_sheet(wb, summary, "Summary");

  // One data sheet per tile
  for (const tile of tiles) {
    const sheetName = `${tile.kpi.id}-${tile.kpi.name}`.slice(0, 31);
    const header = ["period", "value"];
    const rows = tile.data.map((p) => [p.period, p.value]);
    const ws = XLSX.utils.aoa_to_sheet([header, ...rows]);
    ws["!cols"] = [{ wch: 14 }, { wch: 14 }];
    XLSX.utils.book_append_sheet(wb, ws, sheetName);
  }

  // Metadata sheet
  const metaHeader = ["KPI", "Formula", "Unit", "Precision", "Category", "Chart"];
  const metaRows = tiles.map((t) => {
    const f = getFormula(t.kpi.id);
    return [t.kpi.name, f?.formula ?? "", f?.unit ?? "", f?.precision ?? 2, t.kpi.category, t.kpi.chartType];
  });
  const meta = XLSX.utils.aoa_to_sheet([metaHeader, ...metaRows]);
  meta["!cols"] = metaHeader.map(() => ({ wch: 22 }));
  XLSX.utils.book_append_sheet(wb, meta, "Metadata");

  const filename = `${slugify(workspace ?? "workspace")}-${slugify(dashboardName)}-${timestamp()}.xlsx`;
  XLSX.writeFile(wb, filename);
}
